export const INIT_CART_INFO = 'INIT_CART_INFO'
export const TOGGLE_MODEL = 'TOGGLE_MODEL'
export const SELECT_GOODS = 'SELECT_GOODS'
export const SELECT_GROUP = 'SELECT_GROUP'
export const SELECT_ALL = 'SELECT_ALL'
export const UPDATE_CART_GOODS_BY_ID = 'UPDATE_CART_GOODS_BY_ID'
export const DELETE_CART_GOODS_BY_IDS = 'DELETE_CART_GOODS_BY_IDS'
export const CLEAR_CART = 'CLEAR_CART'

export const CART_INDEX = 'CART_INDEX'

export const CART_GOODS_CHECKED = 'CART_GOODS_CHECKED'
export const LoadCarList = 'LoadCarList'
export const LOAD_LIST_GROUP = 'LOAD_LIST_GROUP'

export const LOAD_PAY_SUCCESS = 'LOAD_PAY_SUCCESS'



