DROP TABLE IF EXISTS `coupon_goods_info`;
CREATE TABLE `coupon_goods_info` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `c_id` int(11) DEFAULT '0' COMMENT '种类id',
  `c_name` varchar(50) DEFAULT '' COMMENT '种类',
  `goods_sn` varchar(60) DEFAULT '' COMMENT '商品编号',
  `name` varchar(120) NOT NULL DEFAULT '' COMMENT '商品名称',
  `goods_number` mediumint(8) unsigned DEFAULT '0' COMMENT '商品数量',
  `keywords` varchar(255) DEFAULT '' COMMENT '搜索关键字',
  `goods_brief` varchar(255) DEFAULT '' COMMENT '商品描述',
  `is_on_sale` tinyint(1) unsigned DEFAULT '1' COMMENT '是否在销售  0 :没有,  1: 有,  2: 已售',
  `sort_order` smallint(4) unsigned DEFAULT '100' COMMENT '订单顺序',
  `is_delete` tinyint(1) unsigned DEFAULT '0' COMMENT '是否删除  0 ， 未删除  1， 已删除',
  `eff_time_end` bigint(32) DEFAULT '0' COMMENT '有效时间',
  `redeem_code` varchar(50) DEFAULT '' COMMENT '兑换码（加密）',
  `img_path` varchar(200) DEFAULT NULL COMMENT '图片路径（加密）',
  `vali_code` varchar(300) DEFAULT NULL COMMENT '验证加密完整性（全部加密）',
  `goods_unit` varchar(45) DEFAULT NULL COMMENT '商品单位',
  `is_plat` tinyint(1) DEFAULT 1 COMMENT '是否平台商品: 0 否 1:是',
  `is_used` tinyint(1) DEFAULT 1 COMMENT '是否使用: 0 已使用 1:未使用',
  `cc_id` int(11) DEFAULT NULL COMMENT '客户创建人ID',
  `create_user_id` int(11) DEFAULT NULL COMMENT '创建人ID',
  `update_user_id` int(11) DEFAULT NULL COMMENT '修改人ID',
  `eff_time` datetime DEFAULT NULL COMMENT '有效期',
  `add_time` datetime DEFAULT NULL COMMENT '添加时间',
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`),
  KEY `goods_sn` (`goods_sn`),
  KEY `c_id` (`c_id`),
  KEY `cc_id` (`cc_id`),
  KEY `name` (`name`),
  KEY `is_on_sale` (`is_on_sale`),
  KEY `is_delete` (`is_delete`),
  KEY `eff_time` (`eff_time`),
  KEY `create_user_id` (`create_user_id`),
  KEY `goods_number` (`goods_number`),
  KEY `add_time` (`add_time`),
  KEY `is_plat` (`is_plat`),
  KEY `is_used` (`is_used`),
  KEY `sort_order` (`sort_order`)
) ENGINE=InnoDB AUTO_INCREMENT=666 DEFAULT CHARSET=utf8;
